// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: API/Proto/ProtoContract.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wpar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Wpar) Reset() {
	*x = Wpar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wpar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wpar) ProtoMessage() {}

func (x *Wpar) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wpar.ProtoReflect.Descriptor instead.
func (*Wpar) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{0}
}

type ResponseSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size string `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ResponseSize) Reset() {
	*x = ResponseSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSize) ProtoMessage() {}

func (x *ResponseSize) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSize.ProtoReflect.Descriptor instead.
func (*ResponseSize) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseSize) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Useradrr string `protobuf:"bytes,1,opt,name=useradrr,proto3" json:"useradrr,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetUseradrr() string {
	if x != nil {
		return x.Useradrr
	}
	return ""
}

type Lanb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Lanb) Reset() {
	*x = Lanb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lanb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lanb) ProtoMessage() {}

func (x *Lanb) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lanb.ProtoReflect.Descriptor instead.
func (*Lanb) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{3}
}

func (x *Lanb) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type Chain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InBlock []string `protobuf:"bytes,1,rep,name=InBlock,proto3" json:"InBlock,omitempty"`
}

func (x *Chain) Reset() {
	*x = Chain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{4}
}

func (x *Chain) GetInBlock() []string {
	if x != nil {
		return x.InBlock
	}
	return nil
}

type CandidateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate []string `protobuf:"bytes,1,rep,name=candidate,proto3" json:"candidate,omitempty"`
}

func (x *CandidateList) Reset() {
	*x = CandidateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateList) ProtoMessage() {}

func (x *CandidateList) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateList.ProtoReflect.Descriptor instead.
func (*CandidateList) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{5}
}

func (x *CandidateList) GetCandidate() []string {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type LowData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCandidate string `protobuf:"bytes,1,opt,name=UserCandidate,proto3" json:"UserCandidate,omitempty"`
	Num           uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Passport      string `protobuf:"bytes,3,opt,name=passport,proto3" json:"passport,omitempty"`
	Private       string `protobuf:"bytes,4,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *LowData) Reset() {
	*x = LowData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowData) ProtoMessage() {}

func (x *LowData) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowData.ProtoReflect.Descriptor instead.
func (*LowData) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{6}
}

func (x *LowData) GetUserCandidate() string {
	if x != nil {
		return x.UserCandidate
	}
	return ""
}

func (x *LowData) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *LowData) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *LowData) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

type LowDataChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCandidate string `protobuf:"bytes,1,opt,name=UserCandidate,proto3" json:"UserCandidate,omitempty"`
	Num           uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *LowDataChain) Reset() {
	*x = LowDataChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LowDataChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowDataChain) ProtoMessage() {}

func (x *LowDataChain) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowDataChain.ProtoReflect.Descriptor instead.
func (*LowDataChain) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{7}
}

func (x *LowDataChain) GetUserCandidate() string {
	if x != nil {
		return x.UserCandidate
	}
	return ""
}

func (x *LowDataChain) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type IsComplited struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ic bool `protobuf:"varint,1,opt,name=ic,proto3" json:"ic,omitempty"`
}

func (x *IsComplited) Reset() {
	*x = IsComplited{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsComplited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsComplited) ProtoMessage() {}

func (x *IsComplited) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsComplited.ProtoReflect.Descriptor instead.
func (*IsComplited) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{8}
}

func (x *IsComplited) GetIc() bool {
	if x != nil {
		return x.Ic
	}
	return false
}

type BlockData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum string `protobuf:"bytes,1,opt,name=BlockNum,proto3" json:"BlockNum,omitempty"`
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_Proto_ProtoContract_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_API_Proto_ProtoContract_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_API_Proto_ProtoContract_proto_rawDescGZIP(), []int{9}
}

func (x *BlockData) GetBlockNum() string {
	if x != nil {
		return x.BlockNum
	}
	return ""
}

var File_API_Proto_ProtoContract_proto protoreflect.FileDescriptor

var file_API_Proto_ProtoContract_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x41, 0x50, 0x49, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x57, 0x70, 0x61,
	0x72, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x25, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x61, 0x64, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x61, 0x64, 0x72, 0x72, 0x22, 0x20, 0x0a, 0x04,
	0x4c, 0x61, 0x6e, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x21,
	0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x22, 0x2d, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x77, 0x0a, 0x07, 0x4c, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x4c, 0x6f, 0x77,
	0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x1d, 0x0a, 0x0b, 0x49, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x69, 0x63,
	0x22, 0x27, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x32, 0x80, 0x03, 0x0a, 0x0d, 0x42, 0x4c,
	0x43, 0x48, 0x5f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x57, 0x70, 0x61, 0x72, 0x1a, 0x16, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x2c, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x0e,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x4c, 0x61, 0x6e, 0x62, 0x12, 0x39,
	0x0a, 0x0e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x57, 0x70, 0x61, 0x72,
	0x1a, 0x17, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x08, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x4c, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x1a, 0x15, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x49, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x69, 0x74, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x4c, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x15, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x49, 0x73, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x69, 0x74, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a,
	0x0a, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x57, 0x70, 0x61, 0x72, 0x1a, 0x0f, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x2f, 0x41, 0x50, 0x49, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_API_Proto_ProtoContract_proto_rawDescOnce sync.Once
	file_API_Proto_ProtoContract_proto_rawDescData = file_API_Proto_ProtoContract_proto_rawDesc
)

func file_API_Proto_ProtoContract_proto_rawDescGZIP() []byte {
	file_API_Proto_ProtoContract_proto_rawDescOnce.Do(func() {
		file_API_Proto_ProtoContract_proto_rawDescData = protoimpl.X.CompressGZIP(file_API_Proto_ProtoContract_proto_rawDescData)
	})
	return file_API_Proto_ProtoContract_proto_rawDescData
}

var file_API_Proto_ProtoContract_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_API_Proto_ProtoContract_proto_goTypes = []interface{}{
	(*Wpar)(nil),          // 0: Contract.Wpar
	(*ResponseSize)(nil),  // 1: Contract.ResponseSize
	(*Address)(nil),       // 2: Contract.Address
	(*Lanb)(nil),          // 3: Contract.Lanb
	(*Chain)(nil),         // 4: Contract.Chain
	(*CandidateList)(nil), // 5: Contract.CandidateList
	(*LowData)(nil),       // 6: Contract.LowData
	(*LowDataChain)(nil),  // 7: Contract.LowDataChain
	(*IsComplited)(nil),   // 8: Contract.IsComplited
	(*BlockData)(nil),     // 9: Contract.BlockData
}
var file_API_Proto_ProtoContract_proto_depIdxs = []int32{
	0, // 0: Contract.BLCH_Contract.ChainSize:input_type -> Contract.Wpar
	2, // 1: Contract.BLCH_Contract.Balance:input_type -> Contract.Address
	0, // 2: Contract.BLCH_Contract.ViewCandidates:input_type -> Contract.Wpar
	7, // 3: Contract.BLCH_Contract.Transfer:input_type -> Contract.LowDataChain
	6, // 4: Contract.BLCH_Contract.Vote:input_type -> Contract.LowData
	9, // 5: Contract.BLCH_Contract.TimeBlock:input_type -> Contract.BlockData
	0, // 6: Contract.BLCH_Contract.ChainPrint:input_type -> Contract.Wpar
	1, // 7: Contract.BLCH_Contract.ChainSize:output_type -> Contract.ResponseSize
	3, // 8: Contract.BLCH_Contract.Balance:output_type -> Contract.Lanb
	5, // 9: Contract.BLCH_Contract.ViewCandidates:output_type -> Contract.CandidateList
	8, // 10: Contract.BLCH_Contract.Transfer:output_type -> Contract.IsComplited
	8, // 11: Contract.BLCH_Contract.Vote:output_type -> Contract.IsComplited
	9, // 12: Contract.BLCH_Contract.TimeBlock:output_type -> Contract.BlockData
	4, // 13: Contract.BLCH_Contract.ChainPrint:output_type -> Contract.Chain
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_API_Proto_ProtoContract_proto_init() }
func file_API_Proto_ProtoContract_proto_init() {
	if File_API_Proto_ProtoContract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_API_Proto_ProtoContract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wpar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lanb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LowData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LowDataChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsComplited); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_Proto_ProtoContract_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_API_Proto_ProtoContract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_API_Proto_ProtoContract_proto_goTypes,
		DependencyIndexes: file_API_Proto_ProtoContract_proto_depIdxs,
		MessageInfos:      file_API_Proto_ProtoContract_proto_msgTypes,
	}.Build()
	File_API_Proto_ProtoContract_proto = out.File
	file_API_Proto_ProtoContract_proto_rawDesc = nil
	file_API_Proto_ProtoContract_proto_goTypes = nil
	file_API_Proto_ProtoContract_proto_depIdxs = nil
}
